package d3

import "core:mem"

// The elements of `replay_camera_config.xml` that no route derives, copied
// verbatim out of `finland/finland_rally/route_0/replay_camera_config.xml`.
// Each is one variant over all 104 stock configs, so one copy serves every
// venue.
//
// **The crash camera.** `dynamic_camera_rig` is the camera the terminal-damage
// flow switches to, and the `DynamicCameraRig` element beside it is what places
// it: a hemisphere of 10 placeholders around the car with 10 transitions
// between them. The global `replay/terminal_damage_highlight_control.xml`
// fires `SwitchToDynamicCameraRig`, which finds nothing when a config omits
// the pair. `camera_dyn_-1` and `camera_dyn_+1` ride the progress line by
// `linePointOffset` instead.
//
// Their `Position` and `orientation` are template values, not geometry: one
// value each across all 103 routes of all 10 stock venues, so they are copied
// like everything else here rather than placed on our road.
//
// **The relative cameras.** `pathRelativeToTarget` is what makes their
// coordinates relative. It is on all 414 of the four across the 104 configs
// and on none of the 6130 cameras placed in the world, so a relative camera
// written with a road camera's parameter list is read as world space and parks
// near the origin. `one2watch_camera_spline` names
// `post_podium_camera_bezierControllerPath`, which no stock config defines; it
// is copied dangling, as all 104 ship it.

@(private = "file")
D3_Stock_Element :: struct {
	name:     string,
	attrs:    []Bxml_Attr,
	children: []D3_Stock_Element,
}

@(private = "file")
d3_stock_node :: proc(e: D3_Stock_Element, allocator: mem.Allocator) -> ^Bxml_Node {
	children := make([]^Bxml_Node, len(e.children), allocator)
	for child, i in e.children { children[i] = d3_stock_node(child, allocator) }
	return bxml_node(e.name, e.attrs, children, allocator)
}

// How many of the copied elements are cameras; the rest are the rig and the
// paths those cameras name.
D3_STOCK_CAMERAS :: 7

// Every copied element, in stock's own order: the rig first, then the relative
// cameras, then the paths.
d3_stock_elements :: proc(allocator := context.temp_allocator) -> []^Bxml_Node {
	out := make([]^Bxml_Node, len(D3_STOCK_ELEMENTS), allocator)
	for element, i in D3_STOCK_ELEMENTS { out[i] = d3_stock_node(element, allocator) }
	return out
}

@(private = "file")
D3_STOCK_ELEMENTS := []D3_Stock_Element{
	// The crash camera and its rig. Stock puts these first.
	{"Camera", {{"type", "dynamic"}, {"ident", "dynamic_camera_rig"}, {"sourcePath", ""}, {"assignedToDynamicCameraRig", "true"}}, {
		{"Parameter", {{"name", "Position"}, {"type", "vector3"}, {"x", "-31.802931"}, {"y", "0.456000"}, {"z", "-174.191223"}}, nil},
		{"Parameter", {{"name", "orientation"}, {"type", "Quaternion"}, {"x", "0.003415"}, {"y", "0.953260"}, {"z", "-0.010781"}, {"w", "0.301941"}}, nil},
		{"Parameter", {{"name", "verticalAdjustment"}, {"type", "scalar"}, {"value", "0.500000"}}, nil},
		{"Parameter", {{"name", "horizontalAdjustment"}, {"type", "scalar"}, {"value", "0.500000"}}, nil},
		{"Parameter", {{"name", "dynamicAdjustment"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "lookahead"}, {"type", "scalar"}, {"value", "0.025000"}}, nil},
		{"Parameter", {{"name", "lookaheadMaxAdjustment"}, {"type", "scalar"}, {"value", "0.330000"}}, nil},
		{"Parameter", {{"name", "waitTime"}, {"type", "scalar"}, {"value", "2.250000"}}, nil},
		{"Parameter", {{"name", "waitDistance"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "overZoomPercent"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "overZoomTime"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "targetRadiusCrashZoom"}, {"type", "scalar"}, {"value", "4.500000"}}, nil},
		{"Parameter", {{"name", "zoomInDamping"}, {"type", "scalar"}, {"value", "0.128000"}}, nil},
		{"Parameter", {{"name", "zoomOutDamping"}, {"type", "scalar"}, {"value", "0.128000"}}, nil},
		{"Parameter", {{"name", "useWaitTime"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "useWaitDistance"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "crashZoomEnabled"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "handyCamEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "minNoiseFOV"}, {"type", "scalar"}, {"value", "45.000000"}}, nil},
		{"Parameter", {{"name", "maxNoiseFOV"}, {"type", "scalar"}, {"value", "45.000000"}}, nil},
		{"Parameter", {{"name", "minNoise"}, {"type", "scalar"}, {"value", "0.416000"}}, nil},
		{"Parameter", {{"name", "maxNoise"}, {"type", "scalar"}, {"value", "0.416000"}}, nil},
		{"Parameter", {{"name", "roughness"}, {"type", "scalar"}, {"value", "0.277000"}}, nil},
		{"Parameter", {{"name", "frequency"}, {"type", "scalar"}, {"value", "0.637000"}}, nil},
		{"Parameter", {{"name", "xyTorque"}, {"type", "scalar"}, {"value", "41.618000"}}, nil},
		{"Parameter", {{"name", "zTorque"}, {"type", "scalar"}, {"value", "39.299999"}}, nil},
		{"Parameter", {{"name", "handyCamFractal"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "handyCamHarmonic"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "roll"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "defaultFov"}, {"type", "scalar"}, {"value", "35.000000"}}, nil},
		{"Parameter", {{"name", "minimumFov"}, {"type", "scalar"}, {"value", "35.000000"}}, nil},
		{"Parameter", {{"name", "maximumFov"}, {"type", "scalar"}, {"value", "35.000000"}}, nil},
		{"Parameter", {{"name", "targetOffset"}, {"type", "vector3"}, {"x", "0.000000"}, {"y", "0.6000000"}, {"z", "0.0000"}}, nil},
		{"Parameter", {{"name", "zoomEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "shakeAngle"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeRadius"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeDamping"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "minimumShakeSpeed"}, {"type", "scalar"}, {"value", "20.000000"}}, nil},
		{"Parameter", {{"name", "maximumShakeSpeed"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeScaleX"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeScaleY"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeRotationSpeed"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
	}},
	{"DynamicCameraRig", {{"enable", "true"}, {"hemisphereRadius", "7.000"}, {"maximumVerticalDegree", "60.0"}}, {
		{"PlaceHolder", {{"index", "0"}, {"firstTransition", "0"}, {"horizontalDegree", "45"}, {"verticalDegree", "20"}, {"offsetDistance", "0.000"}, {"lockSpin", "true"}}, nil},
		{"PlaceHolder", {{"index", "1"}, {"firstTransition", "1"}, {"horizontalDegree", "90"}, {"verticalDegree", "20"}, {"offsetDistance", "0.000"}, {"lockSpin", "true"}}, nil},
		{"PlaceHolder", {{"index", "2"}, {"firstTransition", "2"}, {"horizontalDegree", "135"}, {"verticalDegree", "25"}, {"offsetDistance", "0.000"}, {"lockSpin", "true"}}, nil},
		{"PlaceHolder", {{"index", "3"}, {"firstTransition", "3"}, {"horizontalDegree", "225"}, {"verticalDegree", "25"}, {"offsetDistance", "0.000"}, {"lockSpin", "true"}}, nil},
		{"PlaceHolder", {{"index", "4"}, {"firstTransition", "4"}, {"horizontalDegree", "270"}, {"verticalDegree", "20"}, {"offsetDistance", "0.000"}, {"lockSpin", "true"}}, nil},
		{"PlaceHolder", {{"index", "5"}, {"firstTransition", "5"}, {"horizontalDegree", "305"}, {"verticalDegree", "20"}, {"offsetDistance", "0.000"}, {"lockSpin", "true"}}, nil},
		{"PlaceHolder", {{"index", "6"}, {"firstTransition", "6"}, {"horizontalDegree", "45"}, {"verticalDegree", "15"}, {"offsetDistance", "0.000"}, {"lockSpin", "true"}}, nil},
		{"PlaceHolder", {{"index", "7"}, {"firstTransition", "7"}, {"horizontalDegree", "135"}, {"verticalDegree", "15"}, {"offsetDistance", "0.000"}, {"lockSpin", "true"}}, nil},
		{"PlaceHolder", {{"index", "8"}, {"firstTransition", "8"}, {"horizontalDegree", "225"}, {"verticalDegree", "15"}, {"offsetDistance", "0.000"}, {"lockSpin", "true"}}, nil},
		{"PlaceHolder", {{"index", "9"}, {"firstTransition", "9"}, {"horizontalDegree", "315"}, {"verticalDegree", "15"}, {"offsetDistance", "0.000"}, {"lockSpin", "true"}}, nil},
		{"Transition", {{"index", "0"}, {"targetPlaceHolder", "1"}, {"activationTimer", "0.0"}, {"transitionDuration", "1.0"}}, nil},
		{"Transition", {{"index", "1"}, {"targetPlaceHolder", "2"}, {"activationTimer", "0.0"}, {"transitionDuration", "1.0"}}, nil},
		{"Transition", {{"index", "2"}, {"targetPlaceHolder", "3"}, {"activationTimer", "0.0"}, {"transitionDuration", "1.0"}}, nil},
		{"Transition", {{"index", "3"}, {"targetPlaceHolder", "4"}, {"activationTimer", "0.0"}, {"transitionDuration", "1.0"}}, nil},
		{"Transition", {{"index", "4"}, {"targetPlaceHolder", "5"}, {"activationTimer", "0.0"}, {"transitionDuration", "1.0"}}, nil},
		{"Transition", {{"index", "5"}, {"targetPlaceHolder", "6"}, {"activationTimer", "0.0"}, {"transitionDuration", "0.0"}}, nil},
		{"Transition", {{"index", "6"}, {"targetPlaceHolder", "7"}, {"activationTimer", "3.0"}, {"transitionDuration", "0.0"}}, nil},
		{"Transition", {{"index", "7"}, {"targetPlaceHolder", "8"}, {"activationTimer", "3.0"}, {"transitionDuration", "0.0"}}, nil},
		{"Transition", {{"index", "8"}, {"targetPlaceHolder", "9"}, {"activationTimer", "3.0"}, {"transitionDuration", "0.0"}}, nil},
		{"Transition", {{"index", "9"}, {"targetPlaceHolder", "0"}, {"activationTimer", "3.0"}, {"transitionDuration", "0.0"}}, nil},
	}},
	{"Camera", {{"type", "dynamic"}, {"ident", "camera_dyn_-1"}, {"sourcePath", ""}}, {
		{"Parameter", {{"name", "Position"}, {"type", "vector3"}, {"x", "29.447754"}, {"y", "10.556599"}, {"z", "395.397034"}}, nil},
		{"Parameter", {{"name", "orientation"}, {"type", "Quaternion"}, {"x", "0.026404"}, {"y", "0.024887"}, {"z", "-0.000658"}, {"w", "0.999341"}}, nil},
		{"Parameter", {{"name", "verticalAdjustment"}, {"type", "scalar"}, {"value", "0.500000"}}, nil},
		{"Parameter", {{"name", "horizontalAdjustment"}, {"type", "scalar"}, {"value", "0.500000"}}, nil},
		{"Parameter", {{"name", "dynamicAdjustment"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "lookahead"}, {"type", "scalar"}, {"value", "0.025000"}}, nil},
		{"Parameter", {{"name", "lookaheadMaxAdjustment"}, {"type", "scalar"}, {"value", "0.330000"}}, nil},
		{"Parameter", {{"name", "roll"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "radius"}, {"type", "scalar"}, {"value", "4.500000"}}, nil},
		{"Parameter", {{"name", "defaultFov"}, {"type", "scalar"}, {"value", "25.000000"}}, nil},
		{"Parameter", {{"name", "minimumFov"}, {"type", "scalar"}, {"value", "5.000000"}}, nil},
		{"Parameter", {{"name", "maximumFov"}, {"type", "scalar"}, {"value", "55.000000"}}, nil},
		{"Parameter", {{"name", "targetOffset"}, {"type", "vector3"}, {"x", "0.000000"}, {"y", "0.500000"}, {"z", "0.000000"}}, nil},
		{"Parameter", {{"name", "zoomPerSecond"}, {"type", "scalar"}, {"value", "2.000000"}}, nil},
		{"Parameter", {{"name", "zoomEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "turnAcceleration"}, {"type", "scalar"}, {"value", "10.000000"}}, nil},
		{"Parameter", {{"name", "turnDamping"}, {"type", "scalar"}, {"value", "10.000000"}}, nil},
		{"Parameter", {{"name", "maxTurnSpeed"}, {"type", "scalar"}, {"value", "10.000000"}}, nil},
		{"Parameter", {{"name", "turnEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "shakeAngle"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeRadius"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeDamping"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "minimumShakeSpeed"}, {"type", "scalar"}, {"value", "00.000000"}}, nil},
		{"Parameter", {{"name", "maximumShakeSpeed"}, {"type", "scalar"}, {"value", "00.000000"}}, nil},
		{"Parameter", {{"name", "shakeScaleX"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeScaleY"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeRotationSpeed"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "linePointOffset"}, {"type", "int"}, {"value", "-2"}}, nil},
		{"Parameter", {{"name", "positionOffsetForProgressCameras"}, {"type", "vector3"}, {"x", "0"}, {"y", "1"}, {"z", "0"}}, nil},
		{"Parameter", {{"name", "waitTime"}, {"type", "scalar"}, {"value", "3.006"}}, nil},
		{"Parameter", {{"name", "waitDistance"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "overZoomPercent"}, {"type", "scalar"}, {"value", "0.601"}}, nil},
		{"Parameter", {{"name", "overZoomTime"}, {"type", "scalar"}, {"value", "0.569"}}, nil},
		{"Parameter", {{"name", "targetRadiusCrashZoom"}, {"type", "scalar"}, {"value", "6.012"}}, nil},
		{"Parameter", {{"name", "zoomInDamping"}, {"type", "scalar"}, {"value", "0.089"}}, nil},
		{"Parameter", {{"name", "zoomOutDamping"}, {"type", "scalar"}, {"value", "0.027"}}, nil},
		{"Parameter", {{"name", "useWaitTime"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "useWaitDistance"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "crashZoomEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "handyCamEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "minNoiseFOV"}, {"type", "scalar"}, {"value", "45.000000"}}, nil},
		{"Parameter", {{"name", "maxNoiseFOV"}, {"type", "scalar"}, {"value", "45.000000"}}, nil},
		{"Parameter", {{"name", "minNoise"}, {"type", "scalar"}, {"value", "0.416"}}, nil},
		{"Parameter", {{"name", "maxNoise"}, {"type", "scalar"}, {"value", "0.676"}}, nil},
		{"Parameter", {{"name", "roughness"}, {"type", "scalar"}, {"value", "0.399"}}, nil},
		{"Parameter", {{"name", "frequency"}, {"type", "scalar"}, {"value", "6.532"}}, nil},
		{"Parameter", {{"name", "xyTorque"}, {"type", "scalar"}, {"value", "71.676"}}, nil},
		{"Parameter", {{"name", "zTorque"}, {"type", "scalar"}, {"value", "64.74"}}, nil},
		{"Parameter", {{"name", "handyCamFractal"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "handyCamHarmonic"}, {"type", "bool"}, {"value", "true"}}, nil},
	}},
	{"Camera", {{"type", "dynamic"}, {"ident", "camera_dyn_+1"}, {"sourcePath", ""}}, {
		{"Parameter", {{"name", "Position"}, {"type", "vector3"}, {"x", "29.447754"}, {"y", "10.556599"}, {"z", "395.397034"}}, nil},
		{"Parameter", {{"name", "orientation"}, {"type", "Quaternion"}, {"x", "0.026404"}, {"y", "0.024887"}, {"z", "-0.000658"}, {"w", "0.999341"}}, nil},
		{"Parameter", {{"name", "verticalAdjustment"}, {"type", "scalar"}, {"value", "0.500000"}}, nil},
		{"Parameter", {{"name", "horizontalAdjustment"}, {"type", "scalar"}, {"value", "0.500000"}}, nil},
		{"Parameter", {{"name", "dynamicAdjustment"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "lookahead"}, {"type", "scalar"}, {"value", "0.025000"}}, nil},
		{"Parameter", {{"name", "lookaheadMaxAdjustment"}, {"type", "scalar"}, {"value", "0.330000"}}, nil},
		{"Parameter", {{"name", "roll"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "radius"}, {"type", "scalar"}, {"value", "4.500000"}}, nil},
		{"Parameter", {{"name", "defaultFov"}, {"type", "scalar"}, {"value", "25.000000"}}, nil},
		{"Parameter", {{"name", "minimumFov"}, {"type", "scalar"}, {"value", "5.000000"}}, nil},
		{"Parameter", {{"name", "maximumFov"}, {"type", "scalar"}, {"value", "55.000000"}}, nil},
		{"Parameter", {{"name", "targetOffset"}, {"type", "vector3"}, {"x", "0.000000"}, {"y", "0.500000"}, {"z", "0.000000"}}, nil},
		{"Parameter", {{"name", "zoomPerSecond"}, {"type", "scalar"}, {"value", "2.000000"}}, nil},
		{"Parameter", {{"name", "zoomEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "turnAcceleration"}, {"type", "scalar"}, {"value", "10.000000"}}, nil},
		{"Parameter", {{"name", "turnDamping"}, {"type", "scalar"}, {"value", "10.000000"}}, nil},
		{"Parameter", {{"name", "maxTurnSpeed"}, {"type", "scalar"}, {"value", "10.000000"}}, nil},
		{"Parameter", {{"name", "turnEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "shakeAngle"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeRadius"}, {"type", "scalar"}, {"value", "000.000000"}}, nil},
		{"Parameter", {{"name", "shakeDamping"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "minimumShakeSpeed"}, {"type", "scalar"}, {"value", "00.000000"}}, nil},
		{"Parameter", {{"name", "maximumShakeSpeed"}, {"type", "scalar"}, {"value", "00.000000"}}, nil},
		{"Parameter", {{"name", "shakeScaleX"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeScaleY"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeRotationSpeed"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "linePointOffset"}, {"type", "int"}, {"value", "1"}}, nil},
		{"Parameter", {{"name", "positionOffsetForProgressCameras"}, {"type", "vector3"}, {"x", "0"}, {"y", "1"}, {"z", "0"}}, nil},
		{"Parameter", {{"name", "waitTime"}, {"type", "scalar"}, {"value", "3.006"}}, nil},
		{"Parameter", {{"name", "waitDistance"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "overZoomPercent"}, {"type", "scalar"}, {"value", "0.601"}}, nil},
		{"Parameter", {{"name", "overZoomTime"}, {"type", "scalar"}, {"value", "0.569"}}, nil},
		{"Parameter", {{"name", "targetRadiusCrashZoom"}, {"type", "scalar"}, {"value", "6.012"}}, nil},
		{"Parameter", {{"name", "zoomInDamping"}, {"type", "scalar"}, {"value", "0.089"}}, nil},
		{"Parameter", {{"name", "zoomOutDamping"}, {"type", "scalar"}, {"value", "0.027"}}, nil},
		{"Parameter", {{"name", "useWaitTime"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "useWaitDistance"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "crashZoomEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "handyCamEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "minNoiseFOV"}, {"type", "scalar"}, {"value", "45.000000"}}, nil},
		{"Parameter", {{"name", "maxNoiseFOV"}, {"type", "scalar"}, {"value", "45.000000"}}, nil},
		{"Parameter", {{"name", "minNoise"}, {"type", "scalar"}, {"value", "0.416"}}, nil},
		{"Parameter", {{"name", "maxNoise"}, {"type", "scalar"}, {"value", "0.676"}}, nil},
		{"Parameter", {{"name", "roughness"}, {"type", "scalar"}, {"value", "0.399"}}, nil},
		{"Parameter", {{"name", "frequency"}, {"type", "scalar"}, {"value", "6.532"}}, nil},
		{"Parameter", {{"name", "xyTorque"}, {"type", "scalar"}, {"value", "71.676"}}, nil},
		{"Parameter", {{"name", "zTorque"}, {"type", "scalar"}, {"value", "64.74"}}, nil},
		{"Parameter", {{"name", "handyCamFractal"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "handyCamHarmonic"}, {"type", "bool"}, {"value", "true"}}, nil},
	}},

	// The cameras placed relative to a subject rather than in the world.
	{"Camera", {{"type", "zoom"}, {"ident", "relative_service_camera"}, {"sourcePath", "spline_relative_service_camera"}, {"postProcess", "PreRaceDOF"}}, {
		{"Parameter", {{"name", "Position"}, {"type", "vector3"}, {"x", "7.594849"}, {"y", "2.342340"}, {"z", "-2.604227"}}, nil},
		{"Parameter", {{"name", "orientation"}, {"type", "Quaternion"}, {"x", "-0.049793"}, {"y", "-0.158308"}, {"z", "-0.007994"}, {"w", "0.986101"}}, nil},
		{"Parameter", {{"name", "verticalAdjustment"}, {"type", "scalar"}, {"value", "0.500000"}}, nil},
		{"Parameter", {{"name", "horizontalAdjustment"}, {"type", "scalar"}, {"value", "0.500000"}}, nil},
		{"Parameter", {{"name", "dynamicAdjustment"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "lookahead"}, {"type", "scalar"}, {"value", "0.025000"}}, nil},
		{"Parameter", {{"name", "lookaheadMaxAdjustment"}, {"type", "scalar"}, {"value", "0.330000"}}, nil},
		{"Parameter", {{"name", "waitTime"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "waitDistance"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "overZoomPercent"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "overZoomTime"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "targetRadiusCrashZoom"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "zoomInDamping"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "zoomOutDamping"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "useWaitTime"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "useWaitDistance"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "crashZoomEnabled"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "handyCamEnabled"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "minNoiseFOV"}, {"type", "scalar"}, {"value", "45.000000"}}, nil},
		{"Parameter", {{"name", "maxNoiseFOV"}, {"type", "scalar"}, {"value", "45.000000"}}, nil},
		{"Parameter", {{"name", "minNoise"}, {"type", "scalar"}, {"value", "0.416000"}}, nil},
		{"Parameter", {{"name", "maxNoise"}, {"type", "scalar"}, {"value", "0.416000"}}, nil},
		{"Parameter", {{"name", "roughness"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "frequency"}, {"type", "scalar"}, {"value", "0.637000"}}, nil},
		{"Parameter", {{"name", "xyTorque"}, {"type", "scalar"}, {"value", "41.618000"}}, nil},
		{"Parameter", {{"name", "zTorque"}, {"type", "scalar"}, {"value", "39.306000"}}, nil},
		{"Parameter", {{"name", "handyCamFractal"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "handyCamHarmonic"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "roll"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "radius"}, {"type", "scalar"}, {"value", "10.000000"}}, nil},
		{"Parameter", {{"name", "defaultFov"}, {"type", "scalar"}, {"value", "41.000000"}}, nil},
		{"Parameter", {{"name", "minimumFov"}, {"type", "scalar"}, {"value", "41.000000"}}, nil},
		{"Parameter", {{"name", "maximumFov"}, {"type", "scalar"}, {"value", "41.000000"}}, nil},
		{"Parameter", {{"name", "targetOffset"}, {"type", "vector3"}, {"x", "-9.6"}, {"y", "6.4"}, {"z", "22.141001"}}, nil},
		{"Parameter", {{"name", "zoomEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "turnAcceleration"}, {"type", "scalar"}, {"value", "5.000000"}}, nil},
		{"Parameter", {{"name", "turnDamping"}, {"type", "scalar"}, {"value", "5.000000"}}, nil},
		{"Parameter", {{"name", "maxTurnSpeed"}, {"type", "scalar"}, {"value", "5.000000"}}, nil},
		{"Parameter", {{"name", "positionShake"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "rotationShake"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "shakeAngle"}, {"type", "scalar"}, {"value", "10.000000"}}, nil},
		{"Parameter", {{"name", "shakeRadius"}, {"type", "scalar"}, {"value", "4.000000"}}, nil},
		{"Parameter", {{"name", "shakeDamping"}, {"type", "scalar"}, {"value", "5.000000"}}, nil},
		{"Parameter", {{"name", "minimumShakeSpeed"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "maximumShakeSpeed"}, {"type", "scalar"}, {"value", "10.000000"}}, nil},
		{"Parameter", {{"name", "shakeScaleX"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "shakeScaleY"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "shakeRotationSpeed"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "pathRelativeToTarget"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"DynamicRoll", {}, {
			{"Parameter", {{"name", "dRollEnable"}, {"type", "bool"}, {"value", "true"}}, nil},
			{"Parameter", {{"name", "dRollProgressBased"}, {"type", "bool"}, {"value", "true"}}, nil},
			{"Parameter", {{"name", "dRollProgressLooped"}, {"type", "bool"}, {"value", "false"}}, nil},
			{"Parameter", {{"name", "dRollStartRoll"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
			{"Parameter", {{"name", "dRollEndRoll"}, {"type", "scalar"}, {"value", "0.078540"}}, nil},
			{"Parameter", {{"name", "dRollDuration"}, {"type", "scalar"}, {"value", "4.500000"}}, nil},
		}},
	}},
	{"Camera", {{"type", "zoom"}, {"ident", "finish_camera"}, {"sourcePath", "finish_camera_spline"}}, {
		{"Parameter", {{"name", "Position"}, {"type", "vector3"}, {"x", "-2.733417"}, {"y", "0.815219"}, {"z", "3.156549"}}, nil},
		{"Parameter", {{"name", "orientation"}, {"type", "Quaternion"}, {"x", "0.003712"}, {"y", "0.936952"}, {"z", "-0.009957"}, {"w", "0.349296"}}, nil},
		{"Parameter", {{"name", "verticalAdjustment"}, {"type", "scalar"}, {"value", "0.500000"}}, nil},
		{"Parameter", {{"name", "horizontalAdjustment"}, {"type", "scalar"}, {"value", "0.500000"}}, nil},
		{"Parameter", {{"name", "dynamicAdjustment"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "lookahead"}, {"type", "scalar"}, {"value", "0.025000"}}, nil},
		{"Parameter", {{"name", "lookaheadMaxAdjustment"}, {"type", "scalar"}, {"value", "0.330000"}}, nil},
		{"Parameter", {{"name", "waitTime"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "waitDistance"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "overZoomPercent"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "overZoomTime"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "targetRadiusCrashZoom"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "zoomInDamping"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "zoomOutDamping"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "useWaitTime"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "useWaitDistance"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "crashZoomEnabled"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "handyCamEnabled"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "minNoiseFOV"}, {"type", "scalar"}, {"value", "45.000000"}}, nil},
		{"Parameter", {{"name", "maxNoiseFOV"}, {"type", "scalar"}, {"value", "45.000000"}}, nil},
		{"Parameter", {{"name", "minNoise"}, {"type", "scalar"}, {"value", "0.416000"}}, nil},
		{"Parameter", {{"name", "maxNoise"}, {"type", "scalar"}, {"value", "0.416000"}}, nil},
		{"Parameter", {{"name", "roughness"}, {"type", "scalar"}, {"value", "0.277000"}}, nil},
		{"Parameter", {{"name", "frequency"}, {"type", "scalar"}, {"value", "0.637000"}}, nil},
		{"Parameter", {{"name", "xyTorque"}, {"type", "scalar"}, {"value", "41.618000"}}, nil},
		{"Parameter", {{"name", "zTorque"}, {"type", "scalar"}, {"value", "39.306000"}}, nil},
		{"Parameter", {{"name", "handyCamFractal"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "handyCamHarmonic"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "roll"}, {"type", "scalar"}, {"value", "0.087266"}}, nil},
		{"Parameter", {{"name", "defaultFov"}, {"type", "scalar"}, {"value", "48.000000"}}, nil},
		{"Parameter", {{"name", "minimumFov"}, {"type", "scalar"}, {"value", "48.000000"}}, nil},
		{"Parameter", {{"name", "maximumFov"}, {"type", "scalar"}, {"value", "48.000000"}}, nil},
		{"Parameter", {{"name", "targetOffset"}, {"type", "vector3"}, {"x", "0.000000"}, {"y", "0.800000"}, {"z", "0.430000"}}, nil},
		{"Parameter", {{"name", "zoomEnabled"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "turnAcceleration"}, {"type", "scalar"}, {"value", "5.000000"}}, nil},
		{"Parameter", {{"name", "turnDamping"}, {"type", "scalar"}, {"value", "10.000000"}}, nil},
		{"Parameter", {{"name", "maxTurnSpeed"}, {"type", "scalar"}, {"value", "10.000000"}}, nil},
		{"Parameter", {{"name", "turnEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "positionShake"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "rotationShake"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "shakeAngle"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeRadius"}, {"type", "scalar"}, {"value", "5.000000"}}, nil},
		{"Parameter", {{"name", "shakeDamping"}, {"type", "scalar"}, {"value", "5.000000"}}, nil},
		{"Parameter", {{"name", "minimumShakeSpeed"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "maximumShakeSpeed"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeScaleX"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "shakeScaleY"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "shakeRotationSpeed"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "pathRelativeToTarget"}, {"type", "bool"}, {"value", "true"}}, nil},
	}},
	{"Camera", {{"type", "zoom"}, {"ident", "one2watch_camera"}, {"sourcePath", "one2watch_camera_spline"}}, {
		{"Parameter", {{"name", "Position"}, {"type", "vector3"}, {"x", "0"}, {"y", "0"}, {"z", "0"}}, nil},
		{"Parameter", {{"name", "orientation"}, {"type", "Quaternion"}, {"x", "0.003687"}, {"y", "-0.857439"}, {"z", "0.006143"}, {"w", "0.514535"}}, nil},
		{"Parameter", {{"name", "verticalAdjustment"}, {"type", "scalar"}, {"value", "0.500000"}}, nil},
		{"Parameter", {{"name", "horizontalAdjustment"}, {"type", "scalar"}, {"value", "0.500000"}}, nil},
		{"Parameter", {{"name", "dynamicAdjustment"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "lookahead"}, {"type", "scalar"}, {"value", "0.025000"}}, nil},
		{"Parameter", {{"name", "lookaheadMaxAdjustment"}, {"type", "scalar"}, {"value", "0.330000"}}, nil},
		{"Parameter", {{"name", "waitTime"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "waitDistance"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "overZoomPercent"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "overZoomTime"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "targetRadiusCrashZoom"}, {"type", "scalar"}, {"value", "3.300000"}}, nil},
		{"Parameter", {{"name", "zoomInDamping"}, {"type", "scalar"}, {"value", "0.089000"}}, nil},
		{"Parameter", {{"name", "zoomOutDamping"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "useWaitTime"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "useWaitDistance"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "crashZoomEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "handyCamEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "minNoiseFOV"}, {"type", "scalar"}, {"value", "28.092"}}, nil},
		{"Parameter", {{"name", "maxNoiseFOV"}, {"type", "scalar"}, {"value", "56.913"}}, nil},
		{"Parameter", {{"name", "minNoise"}, {"type", "scalar"}, {"value", "0.266"}}, nil},
		{"Parameter", {{"name", "maxNoise"}, {"type", "scalar"}, {"value", "0.312"}}, nil},
		{"Parameter", {{"name", "roughness"}, {"type", "scalar"}, {"value", "0.231"}}, nil},
		{"Parameter", {{"name", "frequency"}, {"type", "scalar"}, {"value", "2.313"}}, nil},
		{"Parameter", {{"name", "xyTorque"}, {"type", "scalar"}, {"value", "150.289"}}, nil},
		{"Parameter", {{"name", "zTorque"}, {"type", "scalar"}, {"value", "80.925"}}, nil},
		{"Parameter", {{"name", "handyCamFractal"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "handyCamHarmonic"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "roll"}, {"type", "scalar"}, {"value", "0.104720"}}, nil},
		{"Parameter", {{"name", "defaultFov"}, {"type", "scalar"}, {"value", "48.000000"}}, nil},
		{"Parameter", {{"name", "targetOffset"}, {"type", "vector3"}, {"x", "0.000000"}, {"y", "0.800000"}, {"z", "0.430000"}}, nil},
		{"Parameter", {{"name", "zoomEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "shakeAngle"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeRadius"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeDamping"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "minimumShakeSpeed"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "maximumShakeSpeed"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeScaleX"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "shakeScaleY"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "shakeRotationSpeed"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "pathRelativeTotarget"}, {"type", "bool"}, {"value", "true"}}, nil},
	}},
	{"Camera", {{"type", "zoom"}, {"ident", "one2watch_camera_RAM"}, {"sourcePath", "one2watch_camera_spline"}}, {
		{"Parameter", {{"name", "Position"}, {"type", "vector3"}, {"x", "0"}, {"y", "0"}, {"z", "0"}}, nil},
		{"Parameter", {{"name", "orientation"}, {"type", "Quaternion"}, {"x", "0.003687"}, {"y", "-0.857439"}, {"z", "0.006143"}, {"w", "0.514535"}}, nil},
		{"Parameter", {{"name", "verticalAdjustment"}, {"type", "scalar"}, {"value", "0.500000"}}, nil},
		{"Parameter", {{"name", "horizontalAdjustment"}, {"type", "scalar"}, {"value", "0.500000"}}, nil},
		{"Parameter", {{"name", "dynamicAdjustment"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "lookahead"}, {"type", "scalar"}, {"value", "0.025000"}}, nil},
		{"Parameter", {{"name", "lookaheadMaxAdjustment"}, {"type", "scalar"}, {"value", "0.330000"}}, nil},
		{"Parameter", {{"name", "waitTime"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "waitDistance"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "overZoomPercent"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "overZoomTime"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "targetRadiusCrashZoom"}, {"type", "scalar"}, {"value", "3.700000"}}, nil},
		{"Parameter", {{"name", "zoomInDamping"}, {"type", "scalar"}, {"value", "0.089000"}}, nil},
		{"Parameter", {{"name", "zoomOutDamping"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "useWaitTime"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "useWaitDistance"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "crashZoomEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "handyCamEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "minNoiseFOV"}, {"type", "scalar"}, {"value", "28.092"}}, nil},
		{"Parameter", {{"name", "maxNoiseFOV"}, {"type", "scalar"}, {"value", "56.913"}}, nil},
		{"Parameter", {{"name", "minNoise"}, {"type", "scalar"}, {"value", "0.266"}}, nil},
		{"Parameter", {{"name", "maxNoise"}, {"type", "scalar"}, {"value", "0.312"}}, nil},
		{"Parameter", {{"name", "roughness"}, {"type", "scalar"}, {"value", "0.231"}}, nil},
		{"Parameter", {{"name", "frequency"}, {"type", "scalar"}, {"value", "2.313"}}, nil},
		{"Parameter", {{"name", "xyTorque"}, {"type", "scalar"}, {"value", "150.289"}}, nil},
		{"Parameter", {{"name", "zTorque"}, {"type", "scalar"}, {"value", "80.925"}}, nil},
		{"Parameter", {{"name", "handyCamFractal"}, {"type", "bool"}, {"value", "false"}}, nil},
		{"Parameter", {{"name", "handyCamHarmonic"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "roll"}, {"type", "scalar"}, {"value", "0.104720"}}, nil},
		{"Parameter", {{"name", "defaultFov"}, {"type", "scalar"}, {"value", "48.000000"}}, nil},
		{"Parameter", {{"name", "targetOffset"}, {"type", "vector3"}, {"x", "0.000000"}, {"y", "1.400000"}, {"z", "0.430000"}}, nil},
		{"Parameter", {{"name", "zoomEnabled"}, {"type", "bool"}, {"value", "true"}}, nil},
		{"Parameter", {{"name", "shakeAngle"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeRadius"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeDamping"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "minimumShakeSpeed"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "maximumShakeSpeed"}, {"type", "scalar"}, {"value", "0.000000"}}, nil},
		{"Parameter", {{"name", "shakeScaleX"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "shakeScaleY"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "shakeRotationSpeed"}, {"type", "scalar"}, {"value", "1.000000"}}, nil},
		{"Parameter", {{"name", "pathRelativeTotarget"}, {"type", "bool"}, {"value", "true"}}, nil},
	}},
// --- paths ---
	{"Path", {{"ident", "spline_relative_service_camera"}, {"type", "spline"}, {"local", "true"}, {"duration", "5"}, {"loop", "false"}, {"percentageCurve", "relative_service_camera_bezierControllerPath"}}, {
		{"Point", {{"x", "7.594849"}, {"y", "2.342340"}, {"z", "-2.604227"}}, nil},
		{"Point", {{"x", "6.322140"}, {"y", "1.617901"}, {"z", "-3.426989"}}, nil},
		{"Point", {{"x", "5.049423"}, {"y", "0.893460"}, {"z", "-4.249750"}}, nil},
		{"Point", {{"x", "3.776722"}, {"y", "0.269022"}, {"z", "-5.072510"}}, nil},
	}},
	{"Path", {{"ident", "finish_camera_spline"}, {"type", "spline"}, {"local", "true"}, {"duration", "3.75"}, {"loop", "false"}, {"percentageCurve", "finish_camera_linearControllerPath"}}, {
		{"Point", {{"x", "-2.733418"}, {"y", "0.815219"}, {"z", "3.156549"}}, nil},
		{"Point", {{"x", "-2.292722"}, {"y", "0.815219"}, {"z", "3.656963"}}, nil},
		{"Point", {{"x", "-1.739175"}, {"y", "0.848764"}, {"z", "4.045237"}}, nil},
		{"Point", {{"x", "-1.118611"}, {"y", "0.896578"}, {"z", "4.289219"}}, nil},
		{"Point", {{"x", "-1.118611"}, {"y", "0.896578"}, {"z", "4.289219"}}, nil},
		{"Point", {{"x", "-0.498047"}, {"y", "0.954360"}, {"z", "4.533202"}}, nil},
		{"Point", {{"x", "0.171715"}, {"y", "1.023520"}, {"z", "4.625888"}}, nil},
		{"Point", {{"x", "0.835215"}, {"y", "1.094101"}, {"z", "4.559602"}}, nil},
		{"Point", {{"x", "0.835215"}, {"y", "1.094101"}, {"z", "4.559602"}}, nil},
		{"Point", {{"x", "1.498716"}, {"y", "1.154086"}, {"z", "4.493316"}}, nil},
		{"Point", {{"x", "2.136904"}, {"y", "1.215219"}, {"z", "4.269962"}}, nil},
		{"Point", {{"x", "2.696936"}, {"y", "1.215219"}, {"z", "3.908034"}}, nil},
	}},
	{"Path", {{"ident", "one2watch_camera_spline"}, {"type", "spline"}, {"local", "true"}, {"duration", "1.000000"}, {"loop", "false"}, {"percentageCurve", "post_podium_camera_bezierControllerPath"}}, {
		{"Point", {{"x", "-1.76725"}, {"y", "1.331763"}, {"z", "4.96154"}}, nil},
		{"Point", {{"x", "-1.76725"}, {"y", "1.331763"}, {"z", "4.96154"}}, nil},
		{"Point", {{"x", "-1.76725"}, {"y", "1.331763"}, {"z", "4.96154"}}, nil},
		{"Point", {{"x", "-1.76725"}, {"y", "1.331763"}, {"z", "4.96154"}}, nil},
	}},
	// post_podium_camera_bezierControllerPath is named by one2watch_camera_spline and defined by no stock config.
	{"Path", {{"ident", "finish_camera_linearControllerPath"}, {"type", "linearPercentage"}}, {
		{"Value", {{"time", "0.000000"}, {"value", "0.000000"}}, nil},
		{"Value", {{"time", "1.000000"}, {"value", "1.000000"}}, nil},
	}},
	{"Path", {{"ident", "relative_service_camera_bezierControllerPath"}, {"type", "bezierPercentage"}}, {
		{"Value", {{"time", "0.000000"}, {"value", "0.000000"}}, nil},
		{"Value", {{"time", "0.333292"}, {"value", "0.333300"}}, nil},
		{"Value", {{"time", "0.666708"}, {"value", "1.000000"}}, nil},
		{"Value", {{"time", "1.000000"}, {"value", "1.000000"}}, nil},
	}},
}
